name: "Cache Swift Dependencies"
description: "Cache Swift PM dependencies with platform-specific paths"
runs:
  using: "composite"
  steps:
    - name: Cache Swift PM dependencies
      uses: namespacelabs/nscloud-cache-action@v1
      with:
        cache: |
          swiftpm
          xcode
        path: random.txt