name: Swift Tests on Cirrus Runners

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}

jobs:
  test-cirrus-macos:
    name: Test on Cirrus Runners macOS
    runs-on: namespace-profile-macos-m4-6cpu-14ram
    steps:
      - uses: actions/checkout@v3
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          detached: true
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - uses: cirruslabs/cache@v4
        with:
          path: .build
          key: .build
      - name: Use Xcode 16.3
        run: xcodes select 16.3
      - name: Build and Test
        run: swift test
