name: Sample App Builds

on:
  # push:
  #   branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  build-sample-app:
    name: Build Sample App (${{ matrix.name }})
    runs-on: namespace-profile-macos-m4-6cpu-14ram
    strategy:
      matrix:
        include:
          - name: "Latest"
            xcode-version: "latest"
          - name: "Stable"
            xcode-version: "latest-stable"
          - name: "Xcode 16"
            xcode-version: "^16.4"
    steps:
      - name: Checkout repository
        uses: namespacelabs/nscloud-checkout-action@v8

      - name: Setup debug session
        uses: ./.github/actions/setup-debug
        with:
          debug_enabled: ${{ github.event.inputs.debug_enabled }}

      - name: Setup mise
        uses: jdx/mise-action@v2

      - name: Use Xcode ${{ matrix.xcode-version }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ matrix.xcode-version }}

      - name: Cache Swift dependencies
        uses: ./.github/actions/cache-swift-deps

      - name: Build Sample App
        run: just sample-app-build-and-run
